"""add_chat_logs

Revision ID: 026b435c4b27
Revises: 018_add_requirements_json
Create Date: 2026-01-20 06:43:53.031033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '026b435c4b27'
down_revision = '018_add_requirements_json'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_templates',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.String(length=1000), nullable=True),
    sa.Column('colors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('client_reminder_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_reminders', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_client_reminders_project_id', table_name='client_reminders')
    op.alter_column('onboarding_data', 'wcag_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_data', 'requirements_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('onboarding_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_onboarding_data_client_access_token', table_name='onboarding_data')
    op.drop_index('ix_onboarding_data_project_id', table_name='onboarding_data')
    op.alter_column('project_tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               nullable=False,
               existing_server_default=sa.text("'NOT_STARTED'::taskstatus"))
    op.alter_column('project_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_project_tasks_project_id', table_name='project_tasks')
    op.drop_index('ix_project_tasks_stage', table_name='project_tasks')
    op.alter_column('projects', 'allow_requirements_exceptions',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sla_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sla_configurations_stage', table_name='sla_configurations')
    op.create_unique_constraint(None, 'sla_configurations', ['stage'])
    op.drop_index('ix_user_leaves_user_dates', table_name='user_leaves')
    op.drop_index('ix_users_manager_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.create_index('ix_user_leaves_user_dates', 'user_leaves', ['user_id', 'start_date', 'end_date'], unique=False)
    op.drop_constraint(None, 'sla_configurations', type_='unique')
    op.create_index('ix_sla_configurations_stage', 'sla_configurations', ['stage'], unique=True)
    op.alter_column('sla_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sla_configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'allow_requirements_exceptions',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_project_tasks_stage', 'project_tasks', ['stage'], unique=False)
    op.create_index('ix_project_tasks_project_id', 'project_tasks', ['project_id'], unique=False)
    op.alter_column('project_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_tasks', 'status',
               existing_type=postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               nullable=True,
               existing_server_default=sa.text("'NOT_STARTED'::taskstatus"))
    op.create_index('ix_onboarding_data_project_id', 'onboarding_data', ['project_id'], unique=False)
    op.create_index('ix_onboarding_data_client_access_token', 'onboarding_data', ['client_access_token'], unique=False)
    op.alter_column('onboarding_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_data', 'requirements_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('onboarding_data', 'wcag_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_client_reminders_project_id', 'client_reminders', ['project_id'], unique=False)
    op.alter_column('client_reminders', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_reminder_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('chat_logs')
    op.drop_table('theme_templates')
    # ### end Alembic commands ###
