"""add_sales_role_and_fields

Revision ID: 0db97cb1d60b
Revises: c67e84d8fc7e
Create Date: 2026-02-04 04:08:27.716198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db97cb1d60b'
down_revision = 'c67e84d8fc7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pmc_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('client_email_ids', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('sales_user_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('manager_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['sales_user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['manager_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'manager_user_id')
    op.drop_column('projects', 'sales_user_id')
    op.drop_column('projects', 'client_email_ids')
    op.drop_column('projects', 'location')
    op.drop_column('projects', 'pmc_name')
    # ### end Alembic commands ###
