"""Add actual_web_url

Revision ID: 2723c2b1a139
Revises: 72854bd2b6e5
Create Date: 2026-01-20 22:53:35.833747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2723c2b1a139'
down_revision = '72854bd2b6e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_templates', sa.Column('actual_web_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme_templates', 'actual_web_url')
    # ### end Alembic commands ###
