"""Add features_json to Project

Revision ID: 72854bd2b6e5
Revises: 026b435c4b27
Create Date: 2026-01-20 07:29:05.394610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72854bd2b6e5'
down_revision = '026b435c4b27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'features_json')
    # ### end Alembic commands ###
