"""add_performance_indexes

Revision ID: 8cf57896ef1a
Revises: 528609c2c319
Create Date: 2026-02-04 12:06:33.381653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf57896ef1a'
down_revision = '528609c2c319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_current_stage'), 'projects', ['current_stage'], unique=False)
    op.create_index(op.f('ix_projects_manager_user_id'), 'projects', ['manager_user_id'], unique=False)
    op.create_index(op.f('ix_projects_sales_user_id'), 'projects', ['sales_user_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_sales_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_manager_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_current_stage'), table_name='projects')
    # ### end Alembic commands ###
