"""add_is_published

Revision ID: 9a00fa19a03d
Revises: 2723c2b1a139
Create Date: 2026-01-20 23:16:39.225578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a00fa19a03d'
down_revision = '2723c2b1a139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_templates', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme_templates', 'is_published')
    # ### end Alembic commands ###
