"""add_onboarding_review_fields

Revision ID: c67e84d8fc7e
Revises: 9a00fa19a03d
Create Date: 2026-02-04 03:52:55.364803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67e84d8fc7e'
down_revision = '9a00fa19a03d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum Type manually for Postgres
    onboardingreviewstatus = sa.Enum('PENDING', 'AI_REVIEWED', 'WAITING_FOR_CONSULTANT', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='onboardingreviewstatus')
    onboardingreviewstatus.create(op.get_bind())
    op.add_column('onboarding_data', sa.Column('review_status', sa.Enum('PENDING', 'AI_REVIEWED', 'WAITING_FOR_CONSULTANT', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='onboardingreviewstatus'), nullable=True))
    op.add_column('onboarding_data', sa.Column('ai_review_notes', sa.Text(), nullable=True))
    op.add_column('onboarding_data', sa.Column('consultant_review_notes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('require_manual_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'require_manual_review')
    op.drop_column('onboarding_data', 'consultant_review_notes')
    op.drop_column('onboarding_data', 'ai_review_notes')
    op.drop_column('onboarding_data', 'review_status')
    
    # Drop Enum type
    onboardingreviewstatus = sa.Enum('PENDING', 'AI_REVIEWED', 'WAITING_FOR_CONSULTANT', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='onboardingreviewstatus')
    onboardingreviewstatus.drop(op.get_bind())
    # ### end Alembic commands ###
