"""
Template catalog: 10 baseline (v1) + 2 versioned (v2) templates for seeding.
"""
from typing import Any, Dict, List

_BASE_PLACEHOLDER_PREVIEW = "https://example.com/previews/{slug}-v{version}"
_BASE_THUMB = "https://placehold.co/600x400?text={text}"

def _thumb(name: str) -> str:
    import urllib.parse
    return _BASE_THUMB.format(text=urllib.parse.quote(name[:30]))


def _preview(slug: str, version: int) -> str:
    return _BASE_PLACEHOLDER_PREVIEW.format(slug=slug, version=version)


_COMMON_PAGES = [
    {"slug": "home", "title": "Home", "sections": ["hero", "features", "cta"]},
    {"slug": "about", "title": "About", "sections": ["story", "team"]},
    {"slug": "contact", "title": "Contact", "sections": ["form", "map"]},
]

_REQUIRED_INPUTS = ["logo", "hero_images", "address", "contact_email", "contact_phone"]
_OPTIONAL_INPUTS = ["social_links", "gallery_images", "floor_plans", "testimonials", "faqs"]


def get_templates_catalog() -> List[Dict[str, Any]]:
    """Return 12 template dicts: 10 v1 baseline + 2 v2 versioned."""
    return [
        {
            "name": "Residential Modern",
            "slug": "residential-modern",
            "version": 1,
            "description": "Clean, modern residential property site with hero, features, and strong CTAs.",
            "category": "residential",
            "style": "modern",
            "feature_tags_json": ["hero", "gallery", "contact", "accessibility_first", "cta"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": True,
            "is_recommended": True,
            "preview_status": "ready",
            "preview_url": _preview("residential-modern", 1),
            "preview_thumbnail_url": _thumb("Residential Modern"),
            "thumbnail_url": _thumb("Residential Modern"),
            "pages_json": _COMMON_PAGES + [{"slug": "properties", "title": "Properties", "sections": ["grid", "filters"]}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#2563eb", "secondary": "#1e40af"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Corporate Property Manager",
            "slug": "corporate-property-manager",
            "version": 1,
            "description": "Professional property management and portfolio presentation.",
            "category": "corporate",
            "style": "professional",
            "feature_tags_json": ["hero", "portfolio", "contact", "case_studies"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": True,
            "preview_status": "ready",
            "preview_url": _preview("corporate-property-manager", 1),
            "preview_thumbnail_url": _thumb("Corporate Property Manager"),
            "thumbnail_url": _thumb("Corporate Property Manager"),
            "pages_json": _COMMON_PAGES + [{"slug": "portfolio", "title": "Portfolio", "sections": ["list", "stats"]}, {"slug": "services", "title": "Services", "sections": []}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS + ["case_studies"],
            "default_config_json": {"colors": {"primary": "#0f766e", "secondary": "#134e4a"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Luxury Lifestyle",
            "slug": "luxury-lifestyle",
            "version": 1,
            "description": "High-end lifestyle and luxury property showcase.",
            "category": "luxury",
            "style": "lifestyle",
            "feature_tags_json": ["hero", "gallery", "testimonials", "luxury"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": True,
            "preview_status": "ready",
            "preview_url": _preview("luxury-lifestyle", 1),
            "preview_thumbnail_url": _thumb("Luxury Lifestyle"),
            "thumbnail_url": _thumb("Luxury Lifestyle"),
            "pages_json": _COMMON_PAGES + [{"slug": "gallery", "title": "Gallery", "sections": ["fullwidth_gallery"]}, {"slug": "testimonials", "title": "Testimonials", "sections": []}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS + ["hero_video_url"],
            "default_config_json": {"colors": {"primary": "#78350f", "secondary": "#92400e"}, "fonts": "Playfair Display", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Student Housing",
            "slug": "student-housing",
            "version": 1,
            "description": "Student and roommate-focused property site.",
            "category": "residential",
            "style": "friendly",
            "feature_tags_json": ["hero", "amenities", "roommate_info", "contact"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("student-housing", 1),
            "preview_thumbnail_url": _thumb("Student Housing"),
            "thumbnail_url": _thumb("Student Housing"),
            "pages_json": _COMMON_PAGES + [{"slug": "amenities", "title": "Amenities", "sections": ["list"]}, {"slug": "roommate", "title": "Roommate Info", "sections": []}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS + ["roommate_info"],
            "default_config_json": {"colors": {"primary": "#4f46e5", "secondary": "#3730a3"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Multi-location Portfolio",
            "slug": "multi-location-portfolio",
            "version": 1,
            "description": "Portfolio for multiple locations and domains.",
            "category": "corporate",
            "style": "portfolio",
            "feature_tags_json": ["multi_location", "portfolio", "locations", "contact"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("multi-location-portfolio", 1),
            "preview_thumbnail_url": _thumb("Multi-location Portfolio"),
            "thumbnail_url": _thumb("Multi-location Portfolio"),
            "pages_json": _COMMON_PAGES + [{"slug": "locations", "title": "Locations", "sections": ["map", "list"]}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS + ["locations"],
            "default_config_json": {"colors": {"primary": "#0369a1", "secondary": "#0c4a6e"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1", "multi_location": True},
            "rules_json": [{"type": "multi_location_toggle", "when": "onboarding indicates multiple locations/domains"}],
            "changelog": "Initial published version",
        },
        {
            "name": "Budget Basic",
            "slug": "budget-basic",
            "version": 1,
            "description": "Simple, fast-loading template for budget deployments.",
            "category": "residential",
            "style": "minimal",
            "feature_tags_json": ["hero", "contact", "lightweight"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("budget-basic", 1),
            "preview_thumbnail_url": _thumb("Budget Basic"),
            "thumbnail_url": _thumb("Budget Basic"),
            "pages_json": [{"slug": "home", "title": "Home", "sections": ["hero", "cta"]}, {"slug": "contact", "title": "Contact", "sections": ["form"]}],
            "required_inputs_json": ["logo", "contact_email", "contact_phone"],
            "optional_inputs_json": ["address", "hero_images"],
            "default_config_json": {"colors": {"primary": "#475569", "secondary": "#334155"}, "fonts": "system", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "High Conversion Landing",
            "slug": "high-conversion-landing",
            "version": 1,
            "description": "One-page high-conversion landing template.",
            "category": "marketing",
            "style": "landing",
            "feature_tags_json": ["one_page", "cta", "conversion", "hero"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("high-conversion-landing", 1),
            "preview_thumbnail_url": _thumb("High Conversion Landing"),
            "thumbnail_url": _thumb("High Conversion Landing"),
            "pages_json": [{"slug": "home", "title": "Home", "sections": ["hero", "benefits", "testimonials", "cta", "form"]}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#dc2626", "secondary": "#b91c1c"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Accessibility First",
            "slug": "accessibility-first",
            "version": 1,
            "description": "WCAG-focused template with semantic structure and strong contrast.",
            "category": "corporate",
            "style": "accessible",
            "feature_tags_json": ["accessibility_first", "wcag", "hero", "contact", "cta"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("accessibility-first", 1),
            "preview_thumbnail_url": _thumb("Accessibility First"),
            "thumbnail_url": _thumb("Accessibility First"),
            "pages_json": _COMMON_PAGES,
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#1e40af", "secondary": "#1e3a8a"}, "fonts": "Inter", "layout": "single", "color_mode": "high_contrast", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Urban Minimal",
            "slug": "urban-minimal",
            "version": 1,
            "description": "Minimal urban aesthetic for city properties.",
            "category": "residential",
            "style": "minimal",
            "feature_tags_json": ["hero", "gallery", "contact", "minimal"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("urban-minimal", 1),
            "preview_thumbnail_url": _thumb("Urban Minimal"),
            "thumbnail_url": _thumb("Urban Minimal"),
            "pages_json": _COMMON_PAGES + [{"slug": "gallery", "title": "Gallery", "sections": ["grid"]}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#1f2937", "secondary": "#111827"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        {
            "name": "Family Suburban Warm",
            "slug": "family-suburban-warm",
            "version": 1,
            "description": "Warm, family-oriented suburban property site.",
            "category": "residential",
            "style": "warm",
            "feature_tags_json": ["hero", "gallery", "contact", "family", "neighborhood"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": False,
            "preview_status": "ready",
            "preview_url": _preview("family-suburban-warm", 1),
            "preview_thumbnail_url": _thumb("Family Suburban Warm"),
            "thumbnail_url": _thumb("Family Suburban Warm"),
            "pages_json": _COMMON_PAGES + [{"slug": "neighborhood", "title": "Neighborhood", "sections": ["map", "schools"]}],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#b45309", "secondary": "#92400e"}, "fonts": "Lato", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "Initial published version",
        },
        # v2: Residential Modern
        {
            "name": "Residential Modern",
            "slug": "residential-modern",
            "version": 2,
            "parent_template_slug": "residential-modern",
            "parent_template_version": 1,
            "description": "Residential Modern v2: improved structure, accessibility, and conversion CTAs.",
            "category": "residential",
            "style": "modern",
            "feature_tags_json": ["hero", "gallery", "contact", "accessibility_first", "cta", "specials", "neighborhood"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": True,
            "preview_status": "ready",
            "preview_url": _preview("residential-modern", 2),
            "preview_thumbnail_url": _thumb("Residential Modern v2"),
            "thumbnail_url": _thumb("Residential Modern v2"),
            "pages_json": _COMMON_PAGES + [
                {"slug": "properties", "title": "Properties", "sections": ["grid", "filters"]},
                {"slug": "specials", "title": "Specials", "sections": ["offers"]},
                {"slug": "neighborhood", "title": "Neighborhood", "sections": ["map", "cta"]},
            ],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS,
            "default_config_json": {"colors": {"primary": "#2563eb", "secondary": "#1e40af"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "v2: Improved structure + accessibility + stronger conversion CTAs.",
        },
        # v2: Corporate Property Manager
        {
            "name": "Corporate Property Manager",
            "slug": "corporate-property-manager",
            "version": 2,
            "parent_template_slug": "corporate-property-manager",
            "parent_template_version": 1,
            "description": "Corporate Property Manager v2: case studies and compliance section.",
            "category": "corporate",
            "style": "professional",
            "feature_tags_json": ["hero", "portfolio", "contact", "case_studies", "compliance"],
            "status": "published",
            "is_published": True,
            "is_active": True,
            "is_default": False,
            "is_recommended": True,
            "preview_status": "ready",
            "preview_url": _preview("corporate-property-manager", 2),
            "preview_thumbnail_url": _thumb("Corporate Property Manager v2"),
            "thumbnail_url": _thumb("Corporate Property Manager v2"),
            "pages_json": _COMMON_PAGES + [
                {"slug": "portfolio", "title": "Portfolio", "sections": ["list", "stats"]},
                {"slug": "services", "title": "Services", "sections": []},
                {"slug": "case-studies", "title": "Case Studies", "sections": ["list"]},
                {"slug": "compliance", "title": "Compliance", "sections": ["compliance"]},
            ],
            "required_inputs_json": _REQUIRED_INPUTS,
            "optional_inputs_json": _OPTIONAL_INPUTS + ["case_studies"],
            "default_config_json": {"colors": {"primary": "#0f766e", "secondary": "#134e4a"}, "fonts": "Inter", "layout": "single", "demo_dataset_key": "pmc_default_v1"},
            "rules_json": [],
            "changelog": "v2: Case studies page + compliance section.",
        },
    ]
