"""
Standard error codes for worker, backend, and audit logs.
Use these in error_json and audit payloads for consistent observability.
"""
from enum import Enum


class ErrorCode(str, Enum):
    OPENAI_ERROR = "OPENAI_ERROR"
    BUILD_VALIDATION_FAILED = "BUILD_VALIDATION_FAILED"
    LIGHTHOUSE_BELOW_FLOOR = "LIGHTHOUSE_BELOW_FLOOR"
    AXE_BLOCKER = "AXE_BLOCKER"
    TEST_FAILURE = "TEST_FAILURE"
    DEFECT_VALIDATION_FAILED = "DEFECT_VALIDATION_FAILED"
    CLIENT_NO_RESPONSE_HOLD = "CLIENT_NO_RESPONSE_HOLD"
    TEMPLATE_MISSING = "TEMPLATE_MISSING"
    TEMPLATE_FALLBACK_PENDING = "TEMPLATE_FALLBACK_PENDING"
    STORAGE_ERROR = "STORAGE_ERROR"
    RENDER_DEPLOY_ERROR = "RENDER_DEPLOY_ERROR"
    TIMEOUT_STUCK_RUN = "TIMEOUT_STUCK_RUN"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    DEFECT_CYCLE_CAP_REACHED = "DEFECT_CYCLE_CAP_REACHED"
    JOB_EXECUTION_ERROR = "JOB_EXECUTION_ERROR"
    CONTRACT_BUILD_ERROR = "CONTRACT_BUILD_ERROR"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
